### ISSUE TITLE
CLI options for bootstrap file

### ISSUE THREAD

**Issue by redaxmedia** [phpbench/phpbench#179]
Hello,

it would be nice to have a <code>-b</code> and <code>--bootstrap</code> options to set the optional bootstrap file.

Thank you

**Comment by dantleech** [comment]
Yes, I think that would make sense.

**Comment by dantleech** [comment]
Currently the bootstrap is defined at the level of the DI configuration - i.e. it is not mutable after the container has been initialized. I have just tried refactoring so that the bootstrap is mutable, but this introduces problems.

The bootstrap filename is available only to the `Launcher` class, which is used by both the `Executor` and `Reflector`. The Reflector needs to bootstrap so that it can instantiate the PHP class in a separate process and extract its reflection data, so the bootstrap needs to be the same for both classes, otherwise things would break, so currently a mutable bootstrap would cause problems.

So, the solution is probably to extract the bootstrap option from `$argv` before the Container is initialized.

**Comment by dantleech** [comment]
Fixed.

**Comment by redaxmedia** [comment]
Works perfect! Think about using semantic versioning... 0.6.0 instead of 0.6 :+1: 

Thank you very much
