### ISSUE TITLE
Option to specify minimum required stability

### ISSUE THREAD

**Issue by dave1010** [phpbench/phpbench#223]
The stability is currently fairly hit and miss. Eg to get a > 90% stability you may need to re-run PHPBench many times.

Adding a "min-stability" or similar global config option and command line argument would allow users to specify the minimum stability they're happy with up front. PHPBench would then keep going until it had reached that stability.

**Comment by dantleech** [comment]
Yeah, this was mentioned last night; basically this already exists in the "retry threshold" feature, so specifying a RT of `1.5` for example would correspond to `93-95%` stability (and there is a global configuration for that). 

However, it would make more sense to specify the target stability instead of the RT.

**Comment by dantleech** [comment]
Actually I think the reason I didn't do this was because the maths is quite hard.

I.e. if you have a set of iterations, and the "minumum stability" is "90%", then how do you know which iterations need to be retried in order that the stability *might* be at least 90%?

The current approach simply says if the percentage difference from the mean for the set is more than a given value (the RT) then resample it.

**Comment by dantleech** [comment]
Closing, this is effectively what `runner.retry_threshold` ensures.
