### ISSUE TITLE
Comments on pull requests

### ISSUE THREAD

**Issue by Nyholm** [phpbench/phpbench#286]
One thing i would really like is a github bot that makes comments on PRs. Just like https://codecov.io/ does. When ever I create a PR i would like to have test result (submitted from travis) and a diff from master. 

That would be a killer feature that let me know how the PR changes the performance of the application.

**Comment by dantleech** [comment]
Yeah, this is indeed the holy grail. Main issue is establishing a stable environment so that results are not dependent on server load - Travis isn't designed to do this, and I havn't been able as yet to establish how effective setting CPU shares in docker is.

Server loads / speeds might be offset by impementing: https://github.com/phpbench/phpbench/issues/269, depending on the success of that it might be feasable to use Travis as a CI service for benchmarks.

In anycase this feature would be a separate project, namely a CI server for benchmarking.

**Comment by dantleech** [comment]
Going to close this as it is out-of-scope for PHPBench. We would need to develop a CI server for running benchmarks.
