### ISSUE TITLE
bootstrap not called until after extensions are loaded

### ISSUE THREAD

**Issue by yuloh** [phpbench/phpbench#405]
I'm adding a custom extension, and I have phpbench installed as a phar.  Since it's a phar install I need to include the autoloader with `"bootstrap": "vendor/autoload.php"`.

It looks like the bootstrap isn't called until after all of the extensions are loaded (from a template?), so my extension fails the `class_exists` test in container and cannot be loaded.

Is there a reason the bootstrap can't be loaded earlier so it can be used to load extensions?

**Comment by dantleech** [comment]
Hmm, indeed. The "bootstrap" is only used for the benchmarks themselves
- the benchmarks are executed in separate processes.

The reason is that PHPBench, when standalone, does not know about your
library autoloader, and is not in the same autoloader namespace and so
cannot conflict or introduce any side-effects into the benchmark.

Until now I have worked under the assumption that people that write
extensions would need to include PHPBench as a `require-dev`.

But this is an issue that should be solved somehow -- as it is also the
reason that the `xdebug` and `dbal` extensions are distributed with
PHPBench instead of being separate packages.

My favourite solution would be to download extensions into the PHPBench
XDG folder and automatically add them to the PHPBench autoloader - but
that is potentially quite some work.

We could also perhaps add a `phpbench_bootstrap` or
`extension_autoload` configuration key.

But short of that, I would advocate using PHPbench as a `require-dev`
dependency - which also has the benefit of locking the PHPBench version
to your benchmark code.

**Comment by yuloh** [comment]
I'm actually benchmarking one of the dependencies of phpbench (justinrainbow/json-schema) and it causes a version conflict if I `require-dev`.

> The reason is that PHPBench, when standalone, does not know about your
library autoloader, and is not in the same autoloader namespace and so
cannot conflict or introduce any side-effects into the benchmark.

That would explain how I am able to use a conflicting version of the phpbench dependency in my benchmarks.

I like the idea of adding a config option for autoloading extensions.  You could easily pass the autoloader instance in to `PhpBench::run` and register the autoload paths there.

**Comment by dantleech** [comment]
Hmm, so I guess we would do something like:

```javascript
{
    ...
    "extensions_autoload": {
        "Acme\\PhpBench\\Extension\\": "path/to/extension/directory"
    }
    "extensions": [
        "Acme\\PhpBench\\Extension\\AcmeExtension"
    ]
}
```

but that wouldn't help with any dependencies the *extension* might have I guess.

**Comment by dantleech** [comment]
I think a possible solution for you now might be to install PHPBench and your extension globally? (as per the installation instructions via. `composer global require`).

Ultimately I think the best solution would be to allow PHPbench to be able to download and extensions on its own, I created the issue #406.

What do you think? I think perhaps the above approach might also permit a `phpbench_extension_directory` option which would contain an `autoload.php` or similar and that could be implemented faster than full extension management via. composer.

**Comment by dantleech** [comment]
I have added the `extension_autoloader` option, see the [documentation](http://phpbench.readthedocs.io/en/latest/extensions/custom.html#phpbench-as-a-phar).

That should provide a way forward, closing, let me know if it works :)
