### ISSUE TITLE
Calculate the probability of a benchmark comparison being valid

### ISSUE THREAD

**Issue by fhein** [phpbench/phpbench#518]
Assume two benchmarks being compared with phpbench report --report=compare. Both were run with --revs -- iterations --retry-threshhold. 

Let's assume also, diff is getting computed (such as b1 is 1.31x b2). 

There wouldn't be to much additional math to apply to to say at what probability the 1.31x difference is valid (i.e. b1 is 1.31x faster than b2 at a probability of 0.85). Applying some math more could give values about the probability in what range the boundaries would be if the probability requirement was predefined (by a config parameter), i.e.. 'b1 is 1.31x seems to be faster than b2 at a propability of 0.97. Respecting the defined stabilty of 0.999 b1 is either max 1.32 times faster than b2 or x times faster than b2.' (with x < 0 indicating that b1 was slower than b2).

Would be great if you'd consider to offer that.

**Comment by dantleech** [comment]
This is where the relative standard deviation comes into play. I think you are also assuming that we have added the diff to the output of that report, so let's assume we can add another column.

The Rstdev gives you a a metric by which you can measure the stability of the results. Given a sufficiently high number of iterations (30 is good, 10 is probably fine) a low Rstdev value (1-2%) means that all of the results were (relatively) very close to eachother.

So, if you take the do `100 - Rstdev` you would probably have something which you could use as a probability score.

**Comment by dantleech** [comment]
e.g. the following:

```
$ ./bin/phpbench report --uuid=tag:impl_a --uuid=tag:impl_b --uuid=tag:impl_c --report='{extends: compare, compare: tag, break:[]}' --report='extends: compare, compare: tag, compare_fields: ["rstdev"], cols: [ benchmark, subject, revs, its]'

+--------------+----------+--------+--------+------+-----------------+-----------------+-----------------+
| benchmark    | subject  | groups | params | revs | tag:impl_a:mean | tag:impl_b:mean | tag:impl_c:mean |
+--------------+----------+--------+--------+------+-----------------+-----------------+-----------------+
| HashingBench | benchMd5 |        | []     | 1000 | 0.957μs         | 0.939μs         | 0.952μs         |
+--------------+----------+--------+--------+------+-----------------+-----------------+-----------------+


+--------------+----------+------+-----+-------------------+-------------------+-------------------+
| benchmark    | subject  | revs | its | tag:impl_a:rstdev | tag:impl_b:rstdev | tag:impl_c:rstdev |
+--------------+----------+------+-----+-------------------+-------------------+-------------------+
| HashingBench | benchMd5 | 1000 | 10  | 4.14%             | 1.79%             | 4.41%             |
+--------------+----------+------+-----+-------------------+-------------------+-------------------+
```

You can see that `impl_a` and `impl_c` have a slighltly high `rstdev`, and you might want to re-run with a retry-threshold (also the iterations in this example could be higher).

**Comment by fhein** [comment]
Partly. More precisely, I am looking some math around the confidence level of a benchmark run. https://en.wikipedia.org/wiki/Confidence_interval.

Example: "At a confidence level of 99%  is 0,345ms < real performance < 0.353ms."

**Comment by dantleech** [comment]
I think confidence intervals apply to a specific sample. Above it seems you are saying that you are f.e. 95% sure that, the for the specific value, `0.345` the _actual_ value lies either 2 standard deviations above or below `0.345` (correct me if I am wrong).

A problem I think is that the actual value is unknowable because unlike a real population, our population (of possible sample values) is infinite.

What we _can_ say is how close the sample values are to each other, this is the relative standard deviation. If you take 100 samples and all of them are `1`, then your RSTDEV is 0%. You can be confident that within the set there was no deviation. What you cannot say however is that the 101th sample will also be 1.

Given two samples `1` and `1000` the relative standard deviation is `99.96%` (not good). `1` and `2` is `33%` (still not good). Given `1`, `1.1` and `0.9` the RSTDEV is around `0.83%` - pretty good, we can be pretty sure that the mean is a good indicator - but it's all dependent on the sample size and the state of your system.

I am not a statistician, so if there are better metrics I am listening, but RSTDEV works for me.

**Comment by fhein** [comment]
My question was about the justification of performance claims, i.e. solver1 is 1,34x faster than solver2. There are some publications around that, f.e. [Benchmarking optimization software with performance profiles](https://pdfs.semanticscholar.org/54a2/0dbd409436be4f188dfa9a78949a1cac230d.pdf). The topic is not all trivial. 

I just wanted to know, if you digged deeper in these materials already, and if so, what your opinion is regarding relevance for php benchmarking. Not meant as a feature request. :)

**Comment by dantleech** [comment]
No I haven't but I will, thanks for the link :)
