### ISSUE TITLE
Add nanosecond time unit

### ISSUE THREAD

**Issue by vladyslavstartsev** [phpbench/phpbench#634]
Since 7.3 there is `hrtime()` which can add nanosecond to this app. Is there a way to add it. So we, php community, can now measure apps performance it nanoseconds?

**Comment by dantleech** [comment]
I did start this in #596

**Comment by dantleech** [comment]
There is still some work to do though - probably want to:

- Probably refactor to make nanoseconds the base unit (rather than scaling up to microseconds)
- Handle the measurement differently on 32 bit vs. 64 bit systems (https://www.php.net/manual/en/function.hrtime) ?
- Add formatting for nano-seconds

**Comment by dantleech** [comment]
Closing this - I don't think it adds any value over microsecond as a float.
